### ISSUE TITLE
【依頼】フリマアプリ挙動確認

### ISSUE THREAD

**Issue by kenken524** [kenken524/furima-39151#20]
#URL
https://furima-39151.onrender.com/

#Basic認証のID
admin

#Basic認証のパスワード
2222

出品者用のメールアドレスとパスワード
test@test
test1234

購入者用のメールアドレスとパスワード
test2@test
test1234

**Comment by snkw-works** [comment]
@kenken524 さん、ご提出ありがとうございます‼︎
正常に動作することが確認できました！ **LGTM** です✨　
おめでとうございます🎉
着実に技術力が身につき、実用的なアプリになってきてますね（^^）

**※確認したのは必須機能のみです。追加実装した機能については確認しておりません。
そのため追加機能を実装している場合は、正しく想定通りの挙動であるか、再度ご自身でご確認をお願い致します。**
**※Github上の最終課題の履歴はここまで頑張ってきた証です。削除せず大切に保管するようにしましょう。**

![lgtm_01](https://user-images.githubusercontent.com/54050089/186354234-2de2a3d1-500d-4164-81d5-7585cdd03227.png)
